Rails.application.routes.draw do
  #post Was generated by scafold 
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#high'
end
